// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZys5lVSEMZqnb51pcaPOPLvZ-7wfbAF0',
    appId: '1:1092508303701:web:9b7ab802f49f04fb2d2fdc',
    messagingSenderId: '1092508303701',
    projectId: 'kus-study',
    authDomain: 'kus-study.firebaseapp.com',
    storageBucket: 'kus-study.appspot.com',
    measurementId: 'G-35PSM2YHSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsb5zuZdFBd3zHnq6-hssaDyvkkGpY-vI',
    appId: '1:1092508303701:android:c92b522e18b958f82d2fdc',
    messagingSenderId: '1092508303701',
    projectId: 'kus-study',
    storageBucket: 'kus-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF6HB0-xUvZvsJsjTkiv-foaAdjVWnUIw',
    appId: '1:1092508303701:ios:2e31bbde784811162d2fdc',
    messagingSenderId: '1092508303701',
    projectId: 'kus-study',
    storageBucket: 'kus-study.appspot.com',
    iosBundleId: 'com.example.kusStudyTogether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF6HB0-xUvZvsJsjTkiv-foaAdjVWnUIw',
    appId: '1:1092508303701:ios:b0857f0e49d5864f2d2fdc',
    messagingSenderId: '1092508303701',
    projectId: 'kus-study',
    storageBucket: 'kus-study.appspot.com',
    iosBundleId: 'com.example.kusStudyTogether.RunnerTests',
  );
}
